accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),

    path('', views.dashboard, name='dashboardd'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('my_orders/', views.my_orders, name='my_orders'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('change_password/', views.change_password, name='change_password'),
    path('order_detail/<int:order_id>/', views.order_detail, name='order_detail'),
    
    path('forget_password/', views.forget_password, name="forget_password"),
    path('resetpassword_validate/<uidb64>/<token>/', views.resetpassword_validate, name='resetpassword_validate'),
    path('reset_password/', views.reset_password, name="reset_password"),
]

cart/urls.py
from django.urls import path
from . import views 

app_name = 'cart'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_cart/<int:product_id>/', views.add_cart, name='add_cart'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', views.remove_cart, name='remove_cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item, name='remove_cart_item'),
    
    
]

core/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('account/', include('accounts.urls', namespace='accounts')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

shop/urls.py
from django.urls import path
from django.utils.regex_helper import normalize
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.home, name='home'),
    path('shop/', views.shop, name='shop'),
    path('shop/<slug:category_slug>/', views.shop, name='categries'),
    path('shop/<slug:category_slug>/<slug:product_details_slug>/', views.product_details, name='product_details'),
    path('run_python_code/', views.run_python_code, name='run_python_code'),
    # path('run_python_code/<int:product_id>/', views.run_python_code, name='run_python_code'),
    path('search/', views.search, name='search'),
    path('review/<int:product_id>/', views.review, name='review'),
]

templates/base.html
{% load static %}

<html class="no-js" lang="">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}S T Y L E - S H O P{% endblock title %}</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/logo.jpg' %}">

    <link rel="apple-touch-icon" href="apple-touch-icon.png' %}">

    
    <link href='https://fonts.googleapis.com/css?family=Lato:400,900,700,300' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Bree+Serif' rel='stylesheet' type='text/css'>

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/animate.css' %}">

    <link rel="stylesheet" href="{% static 'css/materialdesignicons.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/jquery.simpleLens.css' %}">

    <link rel="stylesheet" href="{% static 'css/jquery-ui.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/meanmenu.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/nivo-slider.css' %}">

    <link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">



    
    <style> 
        #searchh input[type=text] {
        width: 150px;
        margin-top:10px;
        margin-bottom:10px;
        box-sizing: border-box;
        border: 2px solid #f4cca4;
        border-radius: 4px;
        font-size: 16px;
        color:#1c1427;
        background-color: #fff;
        background-position: 10px 10px; 
        background-repeat: no-repeat;
        padding: 12px 20px 12px 40px;
        -webkit-transition: width 0.4s ease-in-out;
        transition: width 0.4s ease-in-out;
        }

        #searchh input[type=text]:focus {
        width: 80%;
        }
    </style>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="{% static 'js/vendor/modernizr-2.8.3.min.js' %}"></script>

    <script src="https://www.paypal.com/sdk/js?client-id=ATDakGEFESlSq0xbOzxw0W-dZUWrKfiedaKAFHEk0QKfsUeeR_9j6G1A78TUmvFJuMvz3ArZroEobPHY&currency=USD"></script>
    
</head>

<body style="background:#40394a">

    <!-- header section start -->
    <header style="background:#1c1427" class="header-one header-two">
        <div style="background:#1c1427" class="header-top-two">
            <div class="container text-center">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="middel-top">
                            {% if user.id is None %}
                            <div class="left floatleft">
                                <p style="color:#f4cca4"><b>Welcome Guest!</b></p>
                            </div>
                            {% else %}
                            <div class="left floatleft">
                                <p style="color:#f4cca4"><b>Welcome {{user.first_name | capfirst}}!</b></p>
                            </div>
                            {% endif %}
                        </div>
                        <div class="middel-top clearfix">
                            <ul class="clearfix right floatright">
                                <li>
                                    <a style="color:#f4cca4" href="#"><i class="mdi mdi-account"></i></a>
                                    {% if user.id is None %}
                                    <ul style="background:#1c1427">
                                        <li><a href="{% url 'accounts:login' %}">Login</a></li>
                                        <li><a href="{% url 'accounts:register' %}">Registar</a></li>
                                    </ul>
                                    {% else %}
                                    <ul style="background:#1c1427">
                                        <li><a href="{% url 'accounts:dashboard' %}">Dashboard</a></li>
                                        <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                                    </ul>
                                    {% endif %}
                                </li>
                                <li>
                                    <a style="color:#f4cca4" href="#"><i class="mdi mdi-settings"></i></a>
                                    <ul style="background:#1c1427">
                                        <li><a href="my-account.html">My account</a></li>
                                        <li><a href="cart.html">My cart</a></li>
                                        <li><a href="wishlist.html">My wishlist</a></li>
                                        <li><a href="checkout.html">Check out</a></li>
                                    </ul>
                                </li>
                            </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div style="background:#40394a">
            <div class="container text-center">
                <div class="row">
                    <div class="col-sm-12">
                        <form id="searchh" action={% url 'shop:search' %} method="GET">
                        <input  type="text" name="keyword" placeholder="Search...">
                        <button style="height:49px; margin-bottom:6px; background:#f4cca4;margin-left:-1px;border:None "  class="btn btn-warning" type="submit">
                           <i style="color:#d99879" class="fa fa-search"></i>
                        </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="container text-center">
            <div class="row">
                <div class="col-sm-2">
                    <div class="logo">
                        <a style="color:#f4cca4;font-weight: 800;" href="\"><span
                                style="color:#d99879">S-</span>shop</a>
                    </div>
                </div>
                <div class="col-sm-8">
                    <div class="header-middel">
                        <div class="mainmenu">
                            <nav >
                                <ul>
                                    <li ><a href="\">Home</a></li>
                                    <li><a href="{% url 'shop:shop' %}">Shop</a></li>
                                    <li><a href="#">Category <i class="mdi mdi-arrow-down"></i></a>
                                        <ul class="dropdown">
                                            <li><a href="{% url 'shop:shop' %}">All</a></li>
                                            {% for category in categories %}
                                            <li><a href="{{ category.get_category_slug_url }}">{{category.name}}</a></li>
                                            {% endfor %}
                                        </ul>
                                    </li>
                                </ul>
                            </nav>
                        </div>
                        <!-- mobile menu start -->
                        <div class="mobile-menu-area">
                            <div class="mobile-menu">
                                <nav  id="dropdown">
                                    <ul  >
                                        <li><a style="color:#1c1427" href="\">Home</a></li>
                                        <li><a style="color:#1c1427" href="{% url 'shop:shop' %}">Shop</a></li>
                                        <li><a style="color:#1c1427" href="{% url 'shop:shop' %}">Category</a>
                                            <ul class="dropdown">
                                                <li><a style="color:#1c1427" href="{% url 'shop:shop' %}">All</a></li>
                                                {% for category in categories %}
                                                <li><a style="color:#1c1427" href="{{ category.get_category_slug_url }}">{{category.name}}</a></li>
                                                {% endfor %}
                                            </ul>
                                        </li>
                                    </ul>
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-sm-2">
                    <div class="cart-itmes">
                        <a class="cart-itme-a" href="{% url 'cart:cart' %}">

                            <i class="mdi mdi-cart"></i>
                            {{quantityyy}} items : <strong>₹{{totalll}}</strong>
                        </a>
                        <div class="cartdrop">
                            {% for x in cart_itemsss %}
                            <div class="sin-itme clearfix">
                                <a style="color:#f4cca4" href="{% url 'cart:remove_cart_item' x.product.id x.id %}" onclick="return confirm('Are you really want delete this?')"><i style="background:#ba135d" class="mdi mdi-close"></i></a>
                                <a class="cart-img" href="{{x.product.get_prodcut_details_url}}"><img style="height:108px;width:100%" src="{{x.product.image.url}}" alt="" /></a>
                                <div class="menu-cart-text floatright">
                                    <a href="{{x.product.get_prodcut_details_url}}">
                                        <h5>{{x.product.name}}</h5>
                                    </a>
                                    
                                    {% if x.variation.all %}
                                        {% for item in x.variation.all %}
                                        <span>{{item.variation_category | capfirst}} : {{item.variation_value | capfirst}}</span>
                                        {% endfor %}
                                    {% endif %}
                                    <span>Price for each : ${{x.product.price}}</span>
                                    <span>Quantity : {{x.quantity}}</span>
                                    <strong>${{x.sub_total}}</strong>
                                </div>
                            </div>
                            
                            {% endfor %}
                            
                            <div class="total">
                                <span>total <strong>= ${{totalll}}</strong></span>
                            </div><br>
                            {% if '/cart/' not in request.path %}
                            <a style="background:#40394a;color:#f4cca4" class="out-menu" href="{% url 'cart:cart' %}">Go To Cart</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <br>
    <!--===================== Content ====================-->
    {% block content %}

    {% endblock content %}


    <footer>
        <div  style="background:#3f3350" class="footer-bottom">
            <div class="container">
                <div class="row">
                    <div class="col-xs-12 col-sm-6">
                        <p style="color:#d99879">Created By <span style="color:#f4cca4"><b>PRP GROUP</b></span> 2024 &
                            All Rights Reserved.</p>
                    </div>
                    <div class="col-xs-12 col-sm-6 text-right">
                        <a href="#"><img src="{% static 'img/footer/payment.png' %}" alt="" /></a>
                    </div>
                </div>
            </div>
        </div>
        <!-- footer-bottom area end -->
    </footer>
    <!-- footer section end -->

    <!-- all js here -->
    <!-- jquery latest version -->
    <script src="{% static 'js/vendor/jquery-1.12.3.min.js' %}"></script>
    <!-- bootstrap js -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- owl.carousel js -->
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <!-- meanmenu js -->
    <script src="{% static 'js/jquery.meanmenu.js' %}"></script>
    <!-- countdown JS -->
    <script src="{% static 'js/countdown.js' %}"></script>
    <!-- nivo.slider JS -->
    <script src="{% static 'js/jquery.nivo.slider.pack.js' %}"></script>
    <!-- simpleLens JS -->
    <script src="{% static 'js/jquery.simpleLens.min.js' %}"></script>
    <!-- jquery-ui js -->
    <script src="{% static 'js/jquery-ui.min.js' %}"></script>
    <!-- load-more js -->
    <script src="{% static 'js/load-more.js' %}"></script>
    <!-- plugins js -->
    <script src="{% static 'js/plugins.js' %}"></script>
    <!-- main js -->
    <script src="{% static 'js/main.js' %}"></script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
        $(document).ready(function(){
            $('.thumb a').click(function(e){
                e.preventDefault();
                $('.mainImage img').attr('src', $(this).attr("href"));
                $('.mainImage a').attr('data-lens-image', $(this).attr("data-lens-image"));
            })
        })
    </script>
</body>
</html>